import csv
labeled_questions = [
    ("How do I create a table for my university project?", "Build Table"),
    ("كيف أنشئ جدولًا لمشروعي الجامعي؟", "Build Table"),
    ("What is the best way to design a database table?", "Build Table"),
    ("كيف يمكنني تصميم جدول لقاعدة بيانات؟", "Build Table"),
    ("Can you guide me on building a project timeline table?", "Build Table"),
    ("كيف يمكنني إنشاء جدول زمني لمشروعي؟", "Build Table"),
    ("What format should I use for my project table?", "Build Table"),
    ("ما هو التنسيق الذي يجب أن أستخدمه لجدولي؟", "Build Table"),
    ("How do I export a table from Excel to my project?", "Build Table"),
    ("كيف يمكنني تصدير جدول من Excel إلى مشروعي؟", "Build Table"),
    ("What tools can I use to create a project table?", "Build Table"),
    ("ما الأدوات التي يمكنني استخدامها لإنشاء جدول للمشروع؟", "Build Table"),
    ("Can you show me an example of a project table?", "Build Table"),
    ("هل يمكنك إظهار مثال لجدول مشروع؟", "Build Table"),
    ("What are the key components of a project table?", "Build Table"),
    ("ما هي المكونات الرئيسية لجدول المشروع؟", "Build Table"),
    ("How to align columns in a table properly?", "Build Table"),
    ("كيف يمكنني محاذاة الأعمدة في الجدول بشكل صحيح؟", "Build Table"),
    ("What are best practices for table formatting?", "Build Table"),
    ("ما هي أفضل الممارسات لتنسيق الجداول؟", "Build Table"),
    ("How can I integrate data into my project table?", "Build Table"),
    ("كيف يمكنني دمج البيانات في جدولي للمشروع؟", "Build Table"),
    
    ("What are the opening hours of the university?", "General University Question"),
    ("ما هي ساعات العمل في الجامعة؟", "General University Question"),
    ("Where can I find the academic calendar?", "General University Question"),
    ("أين يمكنني العثور على التقويم الأكاديمي؟", "General University Question"),
    ("How can I register for classes?", "General University Question"),
    ("كيف يمكنني التسجيل في الصفوف؟", "General University Question"),
    ("What is the procedure for changing my major?", "General University Question"),
    ("ما هي إجراءات تغيير التخصص الخاص بي؟", "General University Question"),
    ("When does the semester start?", "General University Question"),
    ("متى يبدأ الفصل الدراسي؟", "General University Question"),
    ("What is the university's policy on attendance?", "General University Question"),
    ("ما هي سياسة الجامعة بشأن الحضور؟", "General University Question"),
    ("Where is the library located?", "General University Question"),
    ("أين تقع المكتبة؟", "General University Question"),
    ("How do I apply for scholarships?", "General University Question"),
    ("كيف يمكنني التقدم للحصول على المنح الدراسية؟", "General University Question"),
    ("What support services are available for students?", "General University Question"),
    ("ما هي خدمات الدعم المتاحة للطلاب؟", "General University Question"),
    ("What are the tuition fees for the upcoming semester?", "General University Question"),
    ("ما هي الرسوم الدراسية للفصل الدراسي القادم؟", "General University Question"),
    ("How can I contact my academic advisor?", "General University Question"),
    ("كيف يمكنني الاتصال بمستشاري الأكاديمي؟", "General University Question"),
    ("Are there any student organizations I can join?", "General University Question"),
    ("هل هناك أي منظمات طلابية يمكنني الانضمام إليها؟", "General University Question"),
    
    ("What software do I need to create a database table?", "Build Table"),
    ("ما البرنامج الذي أحتاجه لإنشاء جدول قاعدة بيانات؟", "Build Table"),
    ("Can I use Google Sheets to create tables?", "Build Table"),
    ("هل يمكنني استخدام Google Sheets لإنشاء جداول؟", "Build Table"),
    ("How do I insert rows into a project table?", "Build Table"),
    ("كيف يمكنني إدراج صفوف في جدول المشروع؟", "Build Table"),
    ("What types of tables can I use in my report?", "Build Table"),
    ("ما أنواع الجداول التي يمكنني استخدامها في تقريري؟", "Build Table"),
    ("How to make a table responsive for web projects?", "Build Table"),
    ("كيف تجعل الجدول متجاوبًا لمشاريع الويب؟", "Build Table"),
    ("What is the best way to present data in a table?", "Build Table"),
    ("ما هي أفضل طريقة لعرض البيانات في جدول؟", "Build Table"),
    ("How to apply formulas in table cells?", "Build Table"),
    ("كيف يمكنني تطبيق الصيغ في خلايا الجدول؟", "Build Table"),
    ("Can I automate table generation in my project?", "Build Table"),
    ("هل يمكنني أتمتة إنشاء الجدول في مشروعي؟", "Build Table"),
    ("What guidelines should I follow for table design?", "Build Table"),
    ("ما هي الإرشادات التي يجب أن أتبعها لتصميم الجدول؟", "Build Table"),
    ("How do I delete a row from my project table?", "Build Table"),
    ("كيف يمكنني حذف صف من جدول مشروعي؟", "Build Table"),
    ("What are the common mistakes in table creation?", "Build Table"),
    ("ما هي الأخطاء الشائعة في إنشاء الجداول؟", "Build Table"),
    ("How to share my project table with others?", "Build Table"),
    ("كيف يمكنني مشاركة جدول مشروعي مع الآخرين؟", "Build Table"),
    
    ("What resources are available for exam preparation?", "General University Question"),
    ("ما هي الموارد المتاحة للتحضير للامتحانات؟", "General University Question"),
    ("How can I improve my study skills?", "General University Question"),
    ("كيف يمكنني تحسين مهاراتي في الدراسة؟", "General University Question"),
    ("What is the best way to find internship opportunities?", "General University Question"),
    ("ما هي أفضل طريقة للعثور على فرص تدريب؟", "General University Question"),
    ("Where can I find information about housing?", "General University Question"),
    ("أين يمكنني العثور على معلومات حول السكن؟", "General University Question"),
    ("What clubs and activities are offered?", "General University Question"),
    ("ما هي الأندية والأنشطة المقدمة؟", "General University Question"),
    ("How do I find a part-time job on campus?", "General University Question"),
    ("كيف يمكنني العثور على وظيفة بدوام جزئي في الحرم الجامعي؟", "General University Question"),
    ("What is the dress code for students?", "General University Question"),
    ("ما هو قانون اللباس للطلاب؟", "General University Question"),
    ("How do I submit a complaint to the university?", "General University Question"),
    ("كيف يمكنني تقديم شكوى إلى الجامعة؟", "General University Question"),
    ("What is the process for academic advising?", "General University Question"),
    ("ما هي عملية التوجيه الأكاديمي؟", "General University Question"),
    ("Are there opportunities for study abroad?", "General University Question"),
    ("هل هناك فرص للدراسة في الخارج؟", "General University Question"),
    ("How can I participate in university events?", "General University Question"),
    ("كيف يمكنني المشاركة في أحداث الجامعة؟", "General University Question"),
    ("What are the benefits of joining student organizations?", "General University Question"),
    ("ما هي فوائد الانضمام إلى المنظمات الطلابية؟", "General University Question"),
]
csv_file = "labeled_questions.csv"
with open(csv_file, mode="w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    # Write the header
    writer.writerow(["Question", "Category"])
    # Write the data
    writer.writerows(labeled_questions)

print(f"Data successfully written to {csv_file}")
