version: '3.8'
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - app/.env  # Point to .env inside the app directory
    depends_on:
      - mongo-local
      - mongo-atlas
    networks:
      - app-network

  mongo-local:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-local-data:/data/db
    networks:
      - app-network

  mongo-atlas:
    image: mongo:6.0
    ports:
      - "27018:27018"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mysecurepassword
    volumes:
      - mongo-atlas-data:/data/db
    command: mongod --port 27018
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-local-data:
  mongo-atlas-data: