version: '3.8'
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    depends_on:
      - mongo-local
      - mongo-atlas
    networks:
      - app-network

  mongo-local:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-local-data:/data/db
    networks:
      - app-network
  mongo-atlas:
    image: mongodb/mongodb-atlas-local
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27018:27017
    volumes:
      - data:/data/db
      - config:/data/configdb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-local-data:
  data:
  config:
